# Generated by Django 4.2.3 on 2024-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_rename_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(max_length=25),
        ),
    ]
